//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPClient.MovieReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovie", ReplyAction="http://tempuri.org/IService1/GetMovieResponse")]
        SOAP_WCF_U_DB.Movie[] GetMovie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovie", ReplyAction="http://tempuri.org/IService1/GetMovieResponse")]
        System.Threading.Tasks.Task<SOAP_WCF_U_DB.Movie[]> GetMovieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMovie", ReplyAction="http://tempuri.org/IService1/AddMovieResponse")]
        void AddMovie(SOAP_WCF_U_DB.Movie newFilm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMovie", ReplyAction="http://tempuri.org/IService1/AddMovieResponse")]
        System.Threading.Tasks.Task AddMovieAsync(SOAP_WCF_U_DB.Movie newFilm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMovie", ReplyAction="http://tempuri.org/IService1/DeleteMovieResponse")]
        void DeleteMovie(SOAP_WCF_U_DB.Movie deleteFilm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMovie", ReplyAction="http://tempuri.org/IService1/DeleteMovieResponse")]
        System.Threading.Tasks.Task DeleteMovieAsync(SOAP_WCF_U_DB.Movie deleteFilm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMovie", ReplyAction="http://tempuri.org/IService1/UpdateMovieResponse")]
        void UpdateMovie(int id, SOAP_WCF_U_DB.Movie film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMovie", ReplyAction="http://tempuri.org/IService1/UpdateMovieResponse")]
        System.Threading.Tasks.Task UpdateMovieAsync(int id, SOAP_WCF_U_DB.Movie film);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TCPClient.MovieReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TCPClient.MovieReference.IService1>, TCPClient.MovieReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAP_WCF_U_DB.Movie[] GetMovie() {
            return base.Channel.GetMovie();
        }
        
        public System.Threading.Tasks.Task<SOAP_WCF_U_DB.Movie[]> GetMovieAsync() {
            return base.Channel.GetMovieAsync();
        }
        
        public void AddMovie(SOAP_WCF_U_DB.Movie newFilm) {
            base.Channel.AddMovie(newFilm);
        }
        
        public System.Threading.Tasks.Task AddMovieAsync(SOAP_WCF_U_DB.Movie newFilm) {
            return base.Channel.AddMovieAsync(newFilm);
        }
        
        public void DeleteMovie(SOAP_WCF_U_DB.Movie deleteFilm) {
            base.Channel.DeleteMovie(deleteFilm);
        }
        
        public System.Threading.Tasks.Task DeleteMovieAsync(SOAP_WCF_U_DB.Movie deleteFilm) {
            return base.Channel.DeleteMovieAsync(deleteFilm);
        }
        
        public void UpdateMovie(int id, SOAP_WCF_U_DB.Movie film) {
            base.Channel.UpdateMovie(id, film);
        }
        
        public System.Threading.Tasks.Task UpdateMovieAsync(int id, SOAP_WCF_U_DB.Movie film) {
            return base.Channel.UpdateMovieAsync(id, film);
        }
    }
}
